### ISSUE TITLE
QGIS crashes if no profile is selected when adding points

### ISSUE THREAD

**Issue by Simon-Lopez** [ptitjano/QGIS#5]
### What is the bug or the crash?

Si un profil n'est pas sélectionné (c'est à dire qu'il n'y a pas encore de repère de projectionselectionné) et un point est rajouté dans une couche en édition, l'application crashe au lieu d'émettre un message d'erreur (ou ne pas permettre l'ajout de point).

### Steps to reproduce the issue

Cf. ci-dessus

### Versions

dev

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Djedouas** [comment]
Eh bien il se trouve que si l'on ajoute un point dans le canvas principal, QGIS crash aussi.

Ce n'est donc pas lié à notre travail en cours sur l'édition à l'intérieur du profil d'élévation.

J'ai fait une [PR sur le dépôt de QGIS](https://github.com/qgis/QGIS/pull/59638) pour régler ça.

**Comment by ptitjano** [comment]
C'est corrigé, on peut fermer.
